FROM python:3.11-slim
WORKDIR /garden
RUN apt-get update && apt-get install -y git && apt-get install -y wget && apt-get install -y dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=/opt/conda/bin:$PATH
RUN conda create -y --name env
RUN pip install "dill==0.3.5.1"
RUN pip install jupyter notebook

RUN pip install "torch==2.1.0+cpu" -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install "torchaudio==2.1.0+cpu" -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install "torchvision==0.16.0+cpu" -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install "torchdata==0.7.0" -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install "torchsummary==1.5.1" -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install "torchtext==0.16.0" -f https://download.pytorch.org/whl/cpu/torch_stable.html

ENTRYPOINT ["jupyter", "notebook", "--notebook-dir=/garden", "--ServerApp.token=791fb91ea2175a1bbf15e1c9606930ebdf6c5fe6a0c3d5bd", "--ip", "0.0.0.0", "--no-browser", "--allow-root"]
