FROM python:3.9-slim
WORKDIR /garden
RUN apt-get update && apt-get install -y git && apt-get install -y wget && apt-get install -y dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.2-0-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=/opt/conda/bin:$PATH
RUN conda create -y --name env
RUN pip install "dill==0.3.5.1"
RUN pip install jupyter notebook

RUN pip install "tensorboard==2.15.0"
RUN pip install "tensorflow-datasets==4.9.3"
RUN pip install "tensorflow-estimator==2.14.0"
RUN pip install "tensorflow-gcs-config==2.14.0"
RUN pip install "tensorflow-hub==0.15.0"
RUN pip install "tensorflow-io-gcs-filesystem==0.34.0"
RUN pip install "tensorflow-metadata==1.14.0"
RUN pip install "tensorflow-probability==0.22.0"
RUN pip install "tensorstore==0.1.46"
RUN pip install "tensorflow==2.14.0"

ENTRYPOINT ["jupyter", "notebook", "--notebook-dir=/garden", "--ServerApp.token=791fb91ea2175a1bbf15e1c9606930ebdf6c5fe6a0c3d5bd", "--ip", "0.0.0.0", "--no-browser", "--allow-root"]
