# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    post_create_environment:
      - pip install uv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --active --group develop
    build:
      html:
        - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv run zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/

mkdocs:
  configuration: mkdocs.yml
