# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry==1.2.2
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-root --no-interaction --no-ansi --with=develop

      # Build documentation in the docs/ directory with mkdocs
mkdocs:
  configuration: mkdocs.yml
