apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-endpoint-instance-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  config.yaml: |
    display_name: {{ coalesce .Values.endpointDisplayName .Values.endpointName .Release.Name }}
    heartbeat_period: 15
    heartbeat_threshold: 200
    funcx_service_address: {{ .Values.funcXServiceAddress }}/v2
    detach_endpoint: False
    engine:
        type: HighThroughputEngine
        provider:
            type: KubernetesProvider
            init_blocks: {{ .Values.initBlocks }}
            min_blocks: {{ .Values.minBlocks }}
            max_blocks: {{ .Values.maxBlocks }}
            init_cpu: {{ .Values.initCPU }}
            max_cpu: {{ .Values.maxCPU }}
            init_mem: {{ .Values.initMem }}
            max_mem: {{ .Values.maxMem }}
            image: {{ .Values.workerImage }}
            worker_init: {{ .Values.workerInit }}
            namespace: {{ .Values.workerNamespace }}
            {{- if .Values.imagePullSecret }}
            secret: {{ .Values.imagePullSecret }}
            {{- end }}
            incluster_config: True
