# Modified from default values for globus_compute_endpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

funcXServiceAddress: https://compute.api.globus.org
image:
  repository: funcx/kube-endpoint
  tag: main-3.11
  pullPolicy: Always

workerDebug: false
workerImage: python:3.11

# workerInit paraphrased for compatibility with legacy dlhub models from
# https://github.com/funcx-faas/funcX/blob/dlhub_deployment_version_0.3/helm/dlhub_values.yaml.
# does the following:
#   - modifies PYTHONPATH for backwards compatibility with dlhub
#   - when running python 3.8 or above, installs globus-compute-endpoint>=2.0
#     - note: capped at globus-compute-endpoint<=2.30, since the manager image (`funcx/kube-endpoint:main-3.11`) no longer seems to be receiving updates past mid-2024 (v2.16.0) and 2.31 is broken for us.
#   - otherwise, install a patched version of globus compute v2.2.3 (the last
#       3.7-compatible version) from github, since the one on pypi is broken.
#       (This only applies to dlhub models; garden never supported 3.7)
workerInit: ulimit -n 1024 && export PYTHONPATH="$PYTHONPATH:/app:/home/ubuntu"; mkdir -p /home/ubuntu/; python -c "import sys; sys.exit(0 if sys.version_info < (3, 8) else 1)" && pip install "git+https://github.com/OwenPriceSkelly/funcX.git@3.7-compatibility-hack#subdirectory=compute_endpoint" || pip install "globus-compute-endpoint<2.31"

# we're restricted to the dlhub namespace on river
workerNamespace: dlhub
logDir: /tmp/worker_logs

# same as defaults but we may want to tweak in the future
initMem: 500Mi
maxMem: 1600Mi
initCPU: 1
maxCPU: 2
initBlocks: 0
minBlocks: 1
maxBlocks: 100
maxWorkersPerPod: 1
maxIdleTime: 3600

# 20min should be generous for a demo endpoint
taskTTLSeconds: 1200

# any additional desired globus-compute-endpoint CLI args
endpointCLIargs: --log-to-console

useClientCredentials: true
useUserCredentials: false
secrets: garden-demo-ep
# ^sets values for env variables:
# FUNCX_SDK_CLIENT_ID=0948a6b0-a622-4078-b0a4-bfd6d77d65cf (client uuid for AI Model Garden registered app)
# FUNCX_SDK_CLIENT_SECRET=...
# secret created 02/26/2024 through globus auth dev portal for AI Model Garden - Owen

# n.b.: this endpoint needed to be "owned by" AI Model Garden app
# so when I first created the endpoint (and it was registered with the globus
# compute service), the FUNCX_SDK_* env vars on my laptop needed to match the
# values in the `garden-demo-ep` kubernetes secret above
# then I had to stop the endpoint locally and re-use the uuid here
endpointUUID: 6ed5d749-abc3-4c83-bcad-80837b3d126f
